"""user model - add varification field (correction)

Revision ID: 64a28842b0ab
Revises: 9cd9d640e071
Create Date: 2022-04-30 18:11:32.689254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a28842b0ab'
down_revision = '9cd9d640e071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
