"""user model - add varification field

Revision ID: 9cd9d640e071
Revises: 17f5a356eb63
Create Date: 2022-04-30 18:00:55.464964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd9d640e071'
down_revision = '17f5a356eb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
