"""datetime - add

Revision ID: a324376fced3
Revises: 74cb010cec53
Create Date: 2022-05-07 13:06:09.351505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a324376fced3'
down_revision = '74cb010cec53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('token_age', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_age')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
